### PR TITLE
Update OSMesa

### LINKED ISSUE #14: Build fails with LLVM master
See https://bugs.freedesktop.org/show_bug.cgi?id=98627.

Updating mesa or backporting https://patchwork.freedesktop.org/patch/120211/ should fix this.

### PR DESCRIPTION
**Pull request by emilio**
Fixes #9 
Fixes #14 

r? @glennw

### CODE REVIEW

**Comment by emilio** [comment]
Oh, to see how I did this, I added a script to this PR, see https://github.com/servo/osmesa-src/blob/a1dbf6a1acc03600056c45355928e9435e71d922/tools/update-mesa.sh

**Comment by jessstrap** [comment]
Just wondering if there is any motion on this?
I am having the same problem from #7 (I'm also on Ubuntu 14.4) and can confirm that the build.rs change fixes it.

**Comment by emilio** [comment]
So this is pretty much blocked on https://github.com/servo/servo/pull/14584, so I should log in into the infra and see what's going on.

**Comment by emilio** [comment]
r? @glennw or @jdm 

(Travis is failing because it's not setup)

**Comment by emilio** [comment]
(@jdm reviewed this over IRC)

**Pull request merged**
