### PR TITLE
build: Enable llvm shared libs.

### LINKED ISSUE #7: llvm linking build break
I have a build break on my Ubuntu 14.04

```
configure: WARNING: Building mesa with statically linked LLVM may cause compilation issues
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5b7): undefined reference to `setupterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e0): undefined reference to `tigetnum'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e9): undefined reference to `set_curterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5f1): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
```

Is it connected with this issue: https://github.com/rust-lang/rust/issues/36854 ? How to make it build?

### PR DESCRIPTION
**Pull request by emilio**
Linking statically to LLVM is not recommended anyway.

This fixes #7

### CODE REVIEW

**Comment by jdm** [comment]
CI shows hundreds and hundreds of linking errors.

**Comment by jdm** [comment]
`llvm-config: error: libLLVM-3.9.so is missing`

**Comment by emilio** [comment]
Huh, CI is green, mod travis... will try to figure it out.

**Comment by emilio** [comment]
(see https://github.com/servo/servo/pull/18889)

**Comment by emilio** [comment]
I have no clue how CI ever worked given https://github.com/servo/osmesa-src/pull/12 never landed...

**Comment by emilio** [comment]
I believe it should work now. Need to go now, but if it does, r? @jdm (with a squash)

**Comment by emilio** [comment]
Or maybe not... sigh

**Comment by emilio** [comment]
Superseded by #24

**Pull request closed without merging**
