### PR TITLE
Add a .travis.yml file

### PR DESCRIPTION
**Pull request by larsbergstrom**
r? @glennw 

(please actually wait for me to OK that https://github.com/servo/saltfs/pull/484 has landed and been pushed to servo-master)

---

This change is [Reviewable](https://reviewable.io/reviews/servo/osmesa-src/3)

### CODE REVIEW

**Comment by larsbergstrom** [comment]
```
No package 'libva' found

Package libva was not found in the pkg-config search path.

Perhaps you should add the directory containing `libva.pc'

to the PKG_CONFIG_PATH environment variable

No package 'libva' found
```

**Comment by larsbergstrom** [comment]
@glennw Do we need another `-l` here?

```
/home/users/aadgrand/LLVM/releases/ubuntu/final/llvm.src/lib/Support/Process.cpp:(.text+0x653): undefined reference to `setupterm'

/home/users/aadgrand/LLVM/releases/ubuntu/final/llvm.src/lib/Support/Process.cpp:(.text+0x663): undefined reference to `tigetnum'

/home/users/aadgrand/LLVM/releases/ubuntu/final/llvm.src/lib/Support/Process.cpp:(.text+0x66f): undefined reference to `set_curterm'

/home/users/aadgrand/LLVM/releases/ubuntu/final/llvm.src/lib/Support/Process.cpp:(.text+0x677): undefined reference to `del_curterm'

collect2: ld returned 1 exit status
```

**Comment by larsbergstrom** [comment]
From http://stackoverflow.com/questions/21477407/llvm-3-5-fails-to-link, it looks like we either need to:
a) `llvm-config --system-libs`
b) add `-ltinfo`

**Comment by larsbergstrom** [comment]
Or just update past `3.4`, as for `3.5` and above of LLVM, osmesa will call `llvm-config --system-libs`...

**Comment by larsbergstrom** [comment]
Hrm, it's still using `/usr/local/clang-3.4` even when I install `clang-3.5`. Gonna have to think / test more for this one (or explicitly pass a different clang version to the osmesa build).

**Comment by emilio** [comment]
Travis now works since #24.

**Pull request closed without merging**
