### PR TITLE
Don't set the number of jobs ourselves but let cargo do it

### PR DESCRIPTION
**Pull request by Eijebong**

### CODE REVIEW

**Comment by Eijebong** [comment]
We should also bump the version, but since the version number seems to be following upstream mesa, this might be weird

**Comment by jdm** [comment]
Just make it 17.3.1-devel.

**Comment by nox** [comment]
@jdm We never published this crate, so what do you think of switching to 0.18?

**Comment by jdm** [comment]
Why?

**Comment by nox** [comment]
Because it's not major, and because following upstream's version if usually a bad idea if you ever need to publish a breaking change specific to that crate.

**Comment by nox** [comment]
Though I don't want to block this with my semver concerns, given this patch doesn't change much on that front.

@bors-servo r+

**Pull request merged**
