### PR TITLE
Exclude the cross-file and force-enable LLVM

### PR DESCRIPTION
**Pull request by kvark**
In order for it to compile on FF CI, we have to provide the `llvm-config` path. This means, being very tied to the environment of execution, and keeping such a cross file in this repo is confusing.

### CODE REVIEW

**Review by staktrace — APPROVED** [review]
LGTM. Presumably you'll be creating the cross file in firefox CI

**Comment by kvark** [comment]
I'm storing it in Firefox, not creating it, but that's not too important, I think

**Comment by staktrace** [comment]
Yeah that's fine.

**Review by emilio — APPROVED** [review]

**Pull request merged**
