### PR TITLE
Migrate CI to Github actions

### PR DESCRIPTION
**Pull request by kvark**

### CODE REVIEW

**Comment by kvark** [comment]
Confirmed on my fork. It runs the check but [fails](https://github.com/kvark/osmesa-src/runs/3732907876?check_suite_focus=true) on the thing that #46 fixes.
@glandium do you want to review/check this script before landing?

**Comment by jdm** [comment]
Ping me when it's time to merge and deploy https://github.com/servo/saltfs/pull/1024.

**Comment by glandium** [comment]
You're installing clang-10/llvm-10, presumably because that's what you want to be using, but the build fails because it's actually using clang-12/llvm-12, so you probably want to set some environment variables to actually build against what you intend to be building against. Or don't install clang-10/llvm-10, since it's not used.

**Comment by kvark** [comment]
Thanks for feedback! Let's see if it passes now.

**Comment by glandium** [comment]
It won't pass, since it will still build with llvm 12 and #46 is not in your branch.

**Comment by kvark** [comment]
yeah, and that's fine. I launched an action with your fix in https://github.com/kvark/osmesa-src/actions/runs/1284836919

**Pull request merged**
