### PR TITLE
LLVM linking

### LINKED ISSUE #7: llvm linking build break
I have a build break on my Ubuntu 14.04

```
configure: WARNING: Building mesa with statically linked LLVM may cause compilation issues
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5b7): undefined reference to `setupterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e0): undefined reference to `tigetnum'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5e9): undefined reference to `set_curterm'
/usr/lib/llvm-3.4/lib/libLLVMSupport.a(Process.o): In function `llvm::sys::Process::FileDescriptorHasColors(int)':
(.text+0x5f1): undefined reference to `del_curterm'
collect2: error: ld returned 1 exit status
```

Is it connected with this issue: https://github.com/rust-lang/rust/issues/36854 ? How to make it build?

### PR DESCRIPTION
**Pull request by mskrzypkows**
fix #7 

I'm not sure if it's proper solution for #7 but it solves build break on my Ubuntu 14.04.

### CODE REVIEW

**Comment by emilio** [comment]
r? @larsbergstrom 

It seems like that could impact our builders. Seems like a sensible solution, I guess. Thanks for looking into it! :)

**Comment by larsbergstrom** [comment]
We'd need to ask @glennw why he added `--disabled-shared-llvm-libs` in the first place. I don't have a big opinion myself on the build machines for whether we link against an existing LLVM installation or build our own, though I suspect that linking against the existing one would also help me with my sadly-stalled https://github.com/servo/osmesa-src/pull/3 :-)

**Comment by glennw** [comment]
I can't recall the exact reason for that flag - I think I was having issues with dynamic library paths on mac without it. The actual ideal solution would be to disable LLVM from the build altogether, if there is a flag for that?

For our test scenario, we specifically want to use the softpipe driver, and not the llvmpipe driver. This is because when running 10,000+ simple tests (like our CI does), the shader compile time with llvmpipe dominates, and so the tests actually run much faster with softpipe :)

Now that we use softpipe driver, it might be safe to remove this flag anyway, since we select the softpipe driver at startup time.

**Comment by glennw** [comment]
If there's no flag to disable llvmpipe from the build, let me know and I'll test this locally on mac + linux, and merge it if all works ok.

**Comment by mskrzypkows** [comment]
> If there's no flag to disable llvmpipe from the build, let me know

@glennw  Who will know that?

**Comment by jdm** [comment]
You could try configuring osmesa with --enable-gallium-llvm=no per https://github.com/servo/osmesa-src/blob/master/mesa-12.0.1/configure.ac#L2082 .

**Comment by mskrzypkows** [comment]
I've tested changes in configure.ac:
`[enable_gallium_llvm=no]`
and second try with:
`[enable_llvm_shared_libs=no]`
none of above code samples works.

But deleting `.arg("--enable-gallium-osmesa")` from build.rs and bringing back `.arg("--disable-llvm-shared-libs")` makes building OK.

**Comment by mskrzypkows** [comment]
Will the patch be merged?

**Comment by glennw** [comment]
@mskrzypkows I'll test with your patch on each platform next week. There was a specific reason for having that flag, so I'll need to test again on each platform before removing it. If all goes well, I'll merge it.

**Comment by emuplz** [comment]
any chance of this being merged? I'm having issues building on OSX due to a strange ncurses linker error too.

**Pull request closed without merging**
